name: Gherkin Linting

on:
  push:
    branches:
      - trunk
      - 'release/**'
    # Only run if feature files are changed.
    paths:
      - '.github/workflows/gherkin-lint.yml'
      - '**.feature'
  pull_request:
    branches:
      - trunk
      - 'release/**'
      - 'feature/**'
    # Only run if feature files are changed.
    paths:
      - '.github/workflows/gherkin-lint.yml'
      - '**.feature'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  gherkin-lint:
    name: Lint Gherkin Feature files
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Run lint
        run: npx --yes gherkin-lint
